configfile: "./config/config.yaml"

# Rules to include
include: "./rules/fastqc.smk"
include: "./rules/merge.smk"


# Define the directory containing the FASTQ files
sample_dir = config["sample_dir"]

# Define the output directory
output_dir = config["output_dir"]

# Define patterns to match specific files
samples = glob_wildcards(f"{sample_dir}/{{sample}}_1_1.fastq.gz").sample


rule all:
    input:
        # This line calls for the fastqc of the merged samples 
        expand("{output_dir}/fastqc/{sample}_mergedF_fastqc.html", 
               sample=samples, 
               output_dir=output_dir),
        # This line calls for the fastqc of the unmerged samples
        expand("{output_dir}/fastqc/{sample}_1_1_fastqc.html", 
               sample=samples, 
               output_dir=output_dir)

rule trim_adapters:
    input:
        fq="data/{sample}.fastq.gz"
    output:
        trimmed="results/trimmed/{sample}_trimmed.fastq.gz"
    log:
        "logs/trim/{sample}.log"
    shell:
        "cutadapt -a AGATCGGAAGAG -o {output.trimmed} {input.fq} > {log} 2>&1"