# Cut and Run configuration file
# Arguments


# Working directory
work_dir: "/slgpfs/projects/rcli/rcli186814/cut_run_vamador"

# Analysis name
analysis_name: "TEST"

# Samples directory
sample_dir: "/home/oscar/Documentos/RNA-Seq_Sample_Files/rna_paired/unmerged"

genome: "data/genome.fa"
peak_caller: "MACS2"

# Output directory
output_dir: "results"

# Configure if there are technical duplicates
technical_duplicates: "yes"


threads: 20