# Cut and Run configuration file
# Arguments


# Working directory
work_dir: "/slgpfs/projects/rcli/rcli186814/cut_run_vamador"

# Analysis name
analysis_name: "TEST"

# Analysis name
extension: "_mergedF"

# Samples directory
sample_dir: "/home/oscar/Documentos/RNA-Seq_Sample_Files/rna_paired/unmerged"

# Output directory
output_dir: "results"

# Configure if there are technical duplicates
technical_duplicates: "yes"

genome: "any"
threads: 20